version: '3.8'

services:
  cobaltia:
    build: ./
    container_name: frog-bot
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: 'redis:alpine'
    container_name: frog-redis
    restart: unless-stopped
