version: '3.8'

services:
  frog-bot:
    build: ./
    container_name: frog-bot
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://frog-redis:6379
    restart: unless-stopped

  frog-redis:
    image: 'redis:alpine'
    container_name: frog-redis
    restart: unless-stopped
